// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

import { implicitReturnType } from '../base/types.js';
import { Exchange as _Exchange } from '../base/Exchange.js';

interface Exchange {
    publicGetPing (params?: {}): Promise<implicitReturnType>;
    publicGetTime (params?: {}): Promise<implicitReturnType>;
    publicGetExchangeInfo (params?: {}): Promise<implicitReturnType>;
    publicGetDepth (params?: {}): Promise<implicitReturnType>;
    publicGetTrades (params?: {}): Promise<implicitReturnType>;
    publicGetHistoricalTrades (params?: {}): Promise<implicitReturnType>;
    publicGetAggTrades (params?: {}): Promise<implicitReturnType>;
    publicGetKlines (params?: {}): Promise<implicitReturnType>;
    publicGetContinuousKlines (params?: {}): Promise<implicitReturnType>;
    publicGetIndexPriceKlines (params?: {}): Promise<implicitReturnType>;
    publicGetMarkPriceKlines (params?: {}): Promise<implicitReturnType>;
    publicGetTicker24hr (params?: {}): Promise<implicitReturnType>;
    publicGetTickerPrice (params?: {}): Promise<implicitReturnType>;
    publicGetTickerBookTicker (params?: {}): Promise<implicitReturnType>;
    publicGetPremiumIndex (params?: {}): Promise<implicitReturnType>;
    publicGetFundingRate (params?: {}): Promise<implicitReturnType>;
    publicGetFundingInfo (params?: {}): Promise<implicitReturnType>;
    publicGetOpenInterest (params?: {}): Promise<implicitReturnType>;
    publicGetOpenInterestHist (params?: {}): Promise<implicitReturnType>;
    publicGetTopLongShortAccountRatio (params?: {}): Promise<implicitReturnType>;
    publicGetTopLongShortPositionRatio (params?: {}): Promise<implicitReturnType>;
    publicGetGlobalLongShortAccountRatio (params?: {}): Promise<implicitReturnType>;
    publicGetLvtKlines (params?: {}): Promise<implicitReturnType>;
    publicGetCompositeIndexResume (params?: {}): Promise<implicitReturnType>;
    privateGetAccount (params?: {}): Promise<implicitReturnType>;
    privateGetBalance (params?: {}): Promise<implicitReturnType>;
    privateGetCommissionRate (params?: {}): Promise<implicitReturnType>;
    privateGetIncome (params?: {}): Promise<implicitReturnType>;
    privateGetLeverageBracket (params?: {}): Promise<implicitReturnType>;
    privateGetPositionRisk (params?: {}): Promise<implicitReturnType>;
    privateGetPositionSideDual (params?: {}): Promise<implicitReturnType>;
    privateGetUserTrades (params?: {}): Promise<implicitReturnType>;
    privateGetOpenOrder (params?: {}): Promise<implicitReturnType>;
    privateGetOpenOrders (params?: {}): Promise<implicitReturnType>;
    privateGetAllOrders (params?: {}): Promise<implicitReturnType>;
    privateGetForceOrders (params?: {}): Promise<implicitReturnType>;
    privateGetAdlQuantile (params?: {}): Promise<implicitReturnType>;
    privatePostOrder (params?: {}): Promise<implicitReturnType>;
    privatePostBatchOrders (params?: {}): Promise<implicitReturnType>;
    privatePostListenKey (params?: {}): Promise<implicitReturnType>;
    privatePostPositionSideDual (params?: {}): Promise<implicitReturnType>;
    privatePostMarginType (params?: {}): Promise<implicitReturnType>;
    privatePostLeverage (params?: {}): Promise<implicitReturnType>;
    privatePostIncomeAsyn (params?: {}): Promise<implicitReturnType>;
    privatePostOrderAmendment (params?: {}): Promise<implicitReturnType>;
    privatePutListenKey (params?: {}): Promise<implicitReturnType>;
    privatePutPositionSideDual (params?: {}): Promise<implicitReturnType>;
    privateDeleteOrder (params?: {}): Promise<implicitReturnType>;
    privateDeleteAllOpenOrders (params?: {}): Promise<implicitReturnType>;
    privateDeleteBatchOrders (params?: {}): Promise<implicitReturnType>;
    privateDeleteListenKey (params?: {}): Promise<implicitReturnType>;
}
abstract class Exchange extends _Exchange {}

export default Exchange;
